"""add meeting feature

Revision ID: 8a5202333ab4
Revises: c8c7f811534f
Create Date: 2025-01-21 03:37:29.058925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8a5202333ab4'
down_revision = 'c8c7f811534f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('owner_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'owner_id')
    # ### end Alembic commands ###
